@indexRoute = http://localhost:4000
@loginRoute = http://localhost:4000/login
@empleadoRoute = http://localhost:4000/empleado


GET {{indexRoute}}

###

POST {{loginRoute}}
Content-Type: application/json

{
    "Correo": "maria@hotmail.com",
    "Contra": "12345"
}

###

GET {{indexRoute}}/tipoPersona